### ISSUE TITLE
Support for multiple connection profiles

### ISSUE THREAD

**Issue by andrewn** [resin-io/resin-wifi-connect#145]
If I'm reading the v3 docs correctly, `WiFi Connect` will only store one network to connect to? The previous behaviour was to maintain a list of networks and credentials. If it could not connect to them, it would start AP mode.

For a user of my project, I think it might be quite annoying to have to re-enter credentials when moving between wifi networks, is there any way/plans to store a list of networks again?

**Comment by majorz** [comment]
We have not changed the behavior in v3 compared to v2. When `--clear=false` is set, the list with connections will be preserved, but the application will not enter AP/captive portal mode. With `--clear=true` it will remove all defined connections and enter AP mode. I just double checked that by running v2 with both options and I confirm that this was the behavior before. On the positive side is that I verified that the new version is much more stable and correct ;)

I agree that the current behavior is a bit limited and confusing and I personally look forward to expanding the functionality and adding support for preserving already entered credentials and entering AP mode at the same time.

**Comment by majorz** [comment]
I am will follow up with more information this week.

**Comment by andrewn** [comment]
Thanks @majorz. I was using v1 before and skipped to v3 so I didn't know about this behaviour.

For my use case I would definitely like the behaviour of being able to enter AP mode whilst preserving previous credentials.

Is this something that's planned? Do you think it's something that would be straightforward to add? I've never used Rust but I'm willing to give it a go and submit a PR.

**Comment by majorz** [comment]
@andrewn I will put it to the top of the priority list. It is the most required feature anyway. What is most important is to define how we will expand the command line usage. Either with new definitions or by expanding the —clear argument values. In a way that more use cases are handled nicely and easy. The —clear argument is not a fine cli api and I am more on the side for deprecating it, but leaving it there till v4. I will be glad to hear your opinion and ideas.

**Comment by andrewn** [comment]
Thanks for the quick reply!

There are a few use cases:

a. Automatically start the AP whenever no Wi-Fi network is joined
b. Force AP mode when `wifi-connect` starts without clearing networks
c. Clear networks

I agree about deprecating `--clear`. I think that the 3 use cases above would be separate CLI arguments and would give `wifi-connect` users more control for different situations.

**Comment by andrewn** [comment]
@majorz Just [looking at the code](https://github.com/resin-io/resin-wifi-connect/blob/master/src/network.rs#L234-L241). It seems that if you have previously never connected to a network, then an AP is created, which is a bit like use case (a) above.

**Comment by majorz** [comment]
@andrewn, thanks for the feedback :) I looked into a few different aspects of the issue. Here is what I came up with and I will bring it up to our team as well to get their feedback.

From the current [state flow diagram](./docs/state-flow-diagram.md) let's look into the capabilities that are directly related to `--clear`:
1. Clear all WiFi connection profiles
2. Activate any existing connection
3. Enter AP/captive portal mode

The `--clear=true` argument does `1` and `3`.  With `false` it is only `2`. We can conclude that `--clear` currently has a broader effect than what one naturally would expect from it.

Additionally, the common pattern for having boolean CLI arguments in Linux is by having two separate flags, e.g. `--clear` for enabling and `--no-clear` for disabling -- that is having two plain flags, instead of a single [yes|no] or [true|false] argument.

Then even if one of those flags is the default behavior, it is also common for both to be present as flags. The reason is that if there is a corresponding environment variable, only by having both flags makes it possible for overwriting the value passed from the environment variable. That is if we have a `CLEAR` env var that takes lower precedence, we need both `--clear` and `--no-clear` to be able to overwrite its value.

Let's see how things will look, if instead of mapping options to use cases, we map those to the capabilities. In our case, this will introduce 3*2=6 new command line flags: `--clear`, `--no-clear`, `--activate`, `--no-activate`, `--portal` and `--no-portal`. The names are sample names as probably better ones can be found.

The current `--clear=true` behavior, which is also the application default behavior, can be translated into the following capabilities flags: `--clear --no-activate --portal`. That makes `--clear`, `--no-activate` and `--portal` the defaults. The translation can be reduced to `--clear --portal`, since `--no-activate` can be assumed on `--clear`.

Then the current `--clear=false` will be: `--no-clear --activate --no-portal`. Or reduced to `--activate --no-portal`, if we make `--no-clear` to be assumed when `--activate` is specified.

The new enhancement we are looking into (supporting AP mode without clearing existing connections) can be defined with `--no-clear --portal` or `--no-clear --activate --portal`. The difference being that in the first case the application will enter AP mode directly, whereas in the second case it will first check whether it is possible to activate an existing connection, and finally enter AP mode, if not able to activate any connection. Since `--portal` is default and `--activate` implies `--no-clear`, those two can be reduced further to just `--no-clear` and `--activate`.

Some of the combination would be incompatible: like having both `--clear` and `--no-clear`, or having both `--activate` and `--clear`. Those can be checked during the configuration phase.

Not very practical, but specifying `--clear --no-portal` (or `--no-portal`) will just clear any existing WiFi connections without doing anything else.

The discussed use cases in short will be:
* `wifi-connect`: delete all WiFi connections and enter AP/captive portal mode.
* `wifi-connect --activate --no-portal`: only try-activate an existing connection.
* `wifi-connect --activate`: try-activate an existing connection and enter AP mode if no activated.
* `wifi-connect --no-clear`: enter AP mode directly.
* `wifi-connect --no-portal`: just delete existing connections.

**Comment by majorz** [comment]
@andrewn, I renamed the issue to `Support for multiple connection profiles`

**Comment by p0wl** [comment]
thanks for the summary. I think `--activate` is covering the most use cases (use working connection if possible, otherwise request a new one), so I would be totally fine with only this flag.

Any idea on how the prio is? I'm not familiar with rust, so not sure if I can contribute.

**Comment by majorz** [comment]
@p0wl we are very close to releasing this. There is some final fixing to be made and hopefully it will be ready before Christmas.

Actually we decided that we are going to drop most of those command line options and the usage will be much simplified. We are dropping the --clear and --activate flags completely, as those are handled by NetworkManager pretty well.

**Comment by p0wl** [comment]
Thanks for the fast response and your work on this!

I you still plan to implement the described desired behaviour (test if existing connection works, if not enter AP mode). Or what do you mean with dropping the `--activate` flag?

**Comment by majorz** [comment]
There will no longer be testing if an existing connection works, that is trying to activate any existing connect:

https://github.com/resin-io/resin-wifi-connect/blob/145-multiple-profiles/docs/state-flow-diagram.md

The reason is that NetworkManager will handle activation on existing connections, so there is no need for WiFi Connect to attempt doing this. If there is no activated connection, then this can be checked outside of WiFi Connect like in the new example start script:

https://github.com/resin-io/resin-wifi-connect/blob/145-multiple-profiles/scripts/start.sh

This is better, since there can be different preconditions for running WiFi Connect as illustrated in the new start.sh.

**Comment by p0wl** [comment]
nice, this is exactly what I needed! This project is making my life so much simpler ❤️

**Comment by andrewn** [comment]
Sorry for the delay in replying to this. I'm really glad it's progressing!

In the meantime I've attempted to get Wifi-Connect to work in this way and came up with [this script](https://github.com/radiodan/provision/blob/master/steps/wifi-connect/files/start-wifi-connect).  It does something similar, using `nm-online` to test for a connection and running `wifi-connect` multiple times to enter access point mode.

Looking forward to the new version 😄 .

**Comment by savnik** [comment]
What is the status of the development?
Very excited to see the result!

**Comment by majorz** [comment]
@savnik, I just finish testing this and next I am going to create a PR and pass it for review. There was a delay because of different issues that I had to fix, but it is all coming together very well now.

**Comment by majorz** [comment]
Version 4 is released now with support for multiple connection profiles. Since this is a major release there was room for other smaller changes (more information in the corresponding PR - https://github.com/resin-io/resin-wifi-connect/pull/157)
