### ISSUE TITLE
Running in both AP mode and as a regular WiFi client at the same time

### ISSUE THREAD

**Issue by bbinet** [resin-io/resin-wifi-connect#150]
This would be useful to keep AP mode always on so that we can always change the actual network parameters.
An example of such a setup would be helpful.

Here is a post which explains how to setup this wifi network configuration on the rpis (without using the network-manager):
http://imti.co/post/145442415333/raspberry-pi-3-wifi-station-ap

Connects to: https://github.com/resin-io/resin-wifi-connect/issues/66#issuecomment-352571800

**Comment by majorz** [comment]
I did some research on this and I am reposting part of the original discussion from our [forums](https://forums.resin.io/t/raspberry-pi3-as-ap-and-wifi-client-station/2519/6?u=majorz): Currently NetworkManager cannot create an AP with the device in being in STA+AP mode. It has a fixed flow for how to handle newly added interfaces. To enter STA+AP mode a virtual interface of type `__ap` has to be added like this: `iw dev wlan0 interface add ap0 type __ap`. After the interface is added NetworkManager forces the interface to enter station/client mode, which does not work, since the interface created with AP type.

(more on that in the forums link above...)

As for WiFi Connect, it uses NetworkManager for creating the AP instead of hostapd, and since using the device in STA+AP mode is not that essential, I do not think we will add support for this (unless future versions of NetworkManager do that). Closing for now as `wontfix`.
