### ISSUE TITLE
Debian Jessie ?

### ISSUE THREAD

**Issue by edeuxk** [resin-io/resin-wifi-connect#197]
Hello I was wondering if the script will work on Jessie?
Do you plan to deploy it or just stay on Strech?

**Comment by majorz** [comment]
It would not work on Debian Jessie directly, since Jessie comes with quite old and incompatible version of NetworkManager: https://packages.debian.org/jessie/net/network-manager

It can be run in a Debian Jessie container on top of resinOS though, since the NetworkManager version in the host OS is very recent. WiFi Connect installed in the container will communicate with the NetworkManager running in the host OS.

It wont work on the older Raspbian versions that are based on Debian Jessie.

**Comment by edeuxk** [comment]
Alright thank you sir.
