### ISSUE TITLE
Using wifi-connect UI portal as optional configuration page ( not force as captive portal )

### ISSUE THREAD

**Issue by jonathangull** [resin-io/resin-wifi-connect#207]
![image](https://user-images.githubusercontent.com/38224533/38513752-d0626edc-3c4c-11e8-9a57-e0effdedf271.png)

Thanks for this great program , very useful for us, we integrated it into our application to provide an optional interface to connect to wifi network when internet is available , rest of the times user will use offline mode with hotspot . Our issue is when user is offline and intends to stay offline but as soon as someone connects to hotspot, the attached sign into wifi message is shown on android phones, on computers(windows 10) a browser tab automatically opens and points to http://go.microsoft.com/fwlink/?LinkID=219472&clcid=0x409 which returns 404

Can we turn this behavior off from within the wificonnect program to treat it as "use when needed ui page"

**Comment by majorz** [comment]
When a user connects to the access point WiFi Connect creates from his phone or computer, the phone or computer will usually detect and show our captive portal UI - that should be at least the case on newer phones or OSes. The 404 error seems like a bug - I think it is because of the /fwlink/ route. I need to test it and fix it. There should not be a 404 error, but the user should see our captive portal.

We are currently improving the experience of integrating WiFi Connect with another applications. WiFi Connect could be run on a different port than 80 as of v4.1.0, which landed yesterday. This way another application may run on port 80 and use WiFi Connect's JSON API, which will be available on a different port. Hopefully by the end of this week I should have a working example for this. I need to finalize how the initial API will look like and document it as well.

Let me send you an update once this is ready, so that we see whether this will fit your use case well and whether we will need additional improvements.

**Comment by jonathangull** [comment]
Thanks @majorz , we are running wificonnect on port 82,  can we avoid the auto sign into wifi/redirect to  http://go.microsoft.com/fwlink/?LinkID=219472&clcid=0x409 that happens at the moment, basically we want user to choose when he wants to go to enter creds and rest of times , wifi connect only acts as proviider of hotspot for hosting our main application

**Comment by majorz** [comment]
Is your application running on port 80? I assume it is. When the user connects to the hotspot, it is more convenient for the users to open your application directly, instead of typing the IP address the hotspot is running on. They do not have to enter wireless credentials when first connected, but just access your web application. In your application you may check what is the request's hostname and redirect the user appropriately to your main page - so that the 404 is avoided. Will that work for you, or maybe I am missing something?

**Comment by jonathangull** [comment]
Thanks @majorz yes my app is running on 80 and opens properly when user types in application url , the issue or request is , as soon as we connect to wifi-connect hotspot, if connection is from a mobile phone (sign into wifi network pop up happens ) and on pc , a browser tab with this address opens directly .
http://go.microsoft.com/fwlink/?LinkID=219472&clcid=0x409 which returns 404

can we avoid these auto opening of popup on mobile and browser tab on pc?

**Comment by majorz** [comment]
Currently this cannot be avoided, but it can be implemented by adding a command line flag for this.

Let me explain how it all works though, because if the 404 is fixed, then it can be more convenient for your users to take advantage of the captive portal detection on the phone or laptop.

When the hotspot is created, it is created by default on 192.168.42.1. When you connect to the network from your phone or laptop, the OS of that device will send a captive portal detection request to a custom address (specific to each OS).

We use dnsmasq to assign addresses to the users connected to the network. Dnsmasq is also used for redirecting all the traffic to the hotspot to 192.168.42.1. Since your web application is listening on port 80, the captive portal detection request will be processed by it. That is to say the http://go.microsoft.com/fwlink/?LinkID=219472&clcid=0x409 request is processed by your application, since dnsmasq redirects the traffic on port 80 to 192.168.42.1:80.

Since your web application does not have a /fwlink/ path handler, it returns 404. You may however process those requests and redirect them to the root / path of your application. This can be done by looking at the hostname in a request middleware (whatever is the usual approach for the web framework you use) to see if it is different from 192.168.42.1 when running in offline mode, or your usual hostname when running in online mode.

This way when users connect to the hotspot WiFi Connect creates, instead of receiving a 404 error, they would be redirected to your application main page. I am talking about the browser tab you mention above.

Would not that work better? If not, can you please explain a bit more why, so that I can understand the use case better?

**Comment by majorz** [comment]
Very nice! Thank you ;)

**Comment by dmckminard** [comment]
Hey @majorz ! Is there a way to disable the opening of the captive portal ?
