### ISSUE TITLE
Wifi-Connect only works once

### ISSUE THREAD

**Issue by cSchubes** [resin-io/resin-wifi-connect#219]
Hi,

I have been playing around with wifi-connect and noticed an interesting issue. If I deploy to my resin device with the appropriate dockerfile, the program will start immediately on boot and allows me to connect my device to the internet. However, if I ssh into the device and attempt to manually run the wifi-connect binary again (from within the docker container), it fails with the following error:

```
Error: Getting the NetworkManager service state failed
  caused by: Service
```
I've tracked it down to the `get_service_state()` call within `start_network_manager_service()` inside the network.rs file. Even if I manually delete the wifi connection previously created by going to /etc/NetworkManager/system-connections on the hostOS, this issue persists. 

I found a band-aid solution in issue #72 using the command `export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket`. Running this then allows me to rerun the binary (and any Rust program that calls `get_service_state()` for that matter.

I don't think this is a long term solution and clearly wifi-connect should be able to run without a fatal error more than once. Any assistance or clarification on this would be great.

**Comment by majorz** [comment]
Right, there is an open issue for detecting whether WiFi Connect is run in a resin container, which will solve the issue with the need to export a new D-Bus address (#121).

There is some clarification in our networking docs in the first note of this section: https://docs.resin.io/reference/resinOS/network/2.x/#changing-the-network-at-runtime

Any calls to the NetworkManager service running in the host OS, which are made from any application running in a container, will need `DBUS_SYSTEM_BUS_ADDRESS` to be exported to the correct path, so that the D-Bus connection to the host OS is established. Without that D-Bus connection will be established to the D-Bus service that runs in the container (if dbus is installed there).

Please let me know if you have more questions (I hope my explanation is not confusing).

**Comment by cSchubes** [comment]
Thank you, that clarifies everything. An easy fix by throwing an ENV line in my Dockerfile to get that variable set at the beginning. Thanks for the quick response.
