### ISSUE TITLE
Using resin-wifi-connect outside the resin.io context

### ISSUE THREAD

**Issue by AdyiPool** [resin-io/resin-wifi-connect#43]
Hello,
 
 Is there a way to only use this project outside the context of resin.io. All I'm looking for if the wifi captive portal functionality to be able to enter the wifi credentials. I'm trying to figure out if there's a way to use this project on a simple Raspbian installation on a RPi3. Thanks in advance!

**Comment by petrosagg** [comment]
Hi @AdyiPool. Yes, you should be able to use this project outside of resin.io. Haven't tried but here are some guidelines.

1. Make sure you're using raspbian jessie, not wheezy
2. Clone the project and `npm install` the dependencies
3. Make sure your system has these dependencies installed https://github.com/resin-io/resin-wifi-connect/blob/master/Dockerfile.template#L4-L11
4. Make sure connman is the connection manager for your device
5. Run `./node_modules/.bin/coffee src/app.coffee`

You'll have to adjust these two env vars because their defaults are set to the values of the resin environment https://github.com/resin-io/resin-wifi-connect/blob/master/src/config.coffee#L7-L8

**Comment by AdyiPool** [comment]
Thanks @petrosagg, I will definitely try it out and report back.

**Comment by petrosagg** [comment]
Closing the issue for now. Feel free to re-open if you try it out and hit any issues
