### ISSUE TITLE
Access point and client at the same time

### ISSUE THREAD

**Issue by larryfant** [resin-io/resin-wifi-connect#48]
Is there reason why access point is not running at the same time when device is connected to wifi network as client?

**Comment by pcarranzav** [comment]
The thing is most wifi dongles don't support this. *Some* do, but since this is a generic solution we went for an approach that works in most cases, which requires disconnecting to open the AP.

**Comment by mercerb** [comment]
My RPi Zero W hasn't once opened the AP, and I've tried it a bunch of times. I have Resin Wifi Connect installed. The thing is, I first set up the RPi with the wifi in my office. When I walk away from the office and lose the wifi signal, RPi still won't set up its own AP. Resin Wifi Connect docs seem to imply that once the RPi has connected to a configured wifi network, it won't create its own AP, even after moving out of range of that network. How do I force a disconnect so that the RPi creates its own AP? Or where can I edit the Resin-Wifi-Connect code to something like "when home network is out of range, create AP"? Thanks!

**Comment by mercerb** [comment]
My RPi Zero W hasn't once opened the AP, and I've tried it a bunch of times. I have Resin Wifi Connect installed. The thing is, I first set up the RPi with the wifi in my office. When I walk away from the office and lose the wifi signal, RPi still won't set up its own AP. Resin Wifi Connect docs seem to imply that once the RPi has connected to a configured wifi network, it won't create its own AP, even after moving out of range of that network. How do I force a disconnect so that the RPi creates its own AP? Or where can I edit the Resin-Wifi-Connect code to something like "when home network is out of range, create AP"? Thanks!

**Comment by josephroberts** [comment]
@mercerb you can run the app with `node src/app.js --clear=true` which will force it to remove the stored credentials and start the access point. You will need some logic in your code to decide when to run resin-wifi-connect, for example; attempt to `ping www.google.com` once per minute and if there is no connection start resin-wifi-connect with the flag `--clear=true`

**Comment by mercerb** [comment]
@josephroberts Thanks so much for the quick response! That seems to do the trick.
