### ISSUE TITLE
If port 80 is already in use by the user app (public url) then capture portal can not also use port 80

### ISSUE THREAD

**Issue by ashleycoker** [resin-io/resin-wifi-connect#64]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ekoz)

**Comment by ashleycoker** [comment]
Can you add to the list for V3 the ability for the hotspot to work on port 80, even if an app is already using it....my node app uses port 80 (public URL) which means the capture portal does not auto load.  I had to change it to use a different port then access it via http://something:1234 in order to set the wifi credentials

**Comment by arthurmoises** [comment]
Hi ashleycoker! I'm facing the same issue. Now, What I'm doing is

```
server.close(function() {
  setWifi();
});
```
And then rebooting the device, so the server connection can start again at port 80. 

I'm creating a spawn process for the change-wifi shell script, but I wish I could spawn a node process for changing the wifi, and when the subprocess finish, re-create the express server connection. For now I'll leave as it, because it's just a demo, and we're are focusing on other parts of the application, but I want to get better at doing this sort of thing with nodejs. 

I think I must embed the Dbus part of the shell script inside the app.coffee of resin-wifi-connect. But hasn't tested yet. Any thoughts?

**Comment by iamxuxiao** [comment]
similar use case.  I wish not want to integrate this coffeescript into my existing nodejs service.  that means my other app is going to listen to port 80 too.  any workaround/pointers ?

**Comment by aj-ptw** [comment]
I'm facing the same problem, I wanted to use an express app on port 80 that tells the wifi config portal to start. I guess I should return a success message, close the server, then start the wifi config script.

**Comment by aj-ptw** [comment]
WOW this fixed my problem!

**Comment by majorz** [comment]
Closing this as fixed, as we introduced a command line argument + env var for this:
```
-o, --portal-listening-port listening_port, $PORTAL_LISTENING_PORT`.

Listening port of the captive portal web server

Default: 80
```
