### ISSUE TITLE
Can we configure which wlan interface is picked up ?

### ISSUE THREAD

**Issue by benoitguigal** [resin-io/resin-wifi-connect#81]
If we connect a WiFi dongle to a Raspberry Pi 3, how do we know if resin-connect is using the onboard WiFi chipset or the dongle ?

**Comment by imrehg** [comment]
I think it should try to use the interface that comes up as `wlan0`. Some more discussion about using RPi3 with an additional dongle is [in the forums](https://forums.resin.io/t/raspberry-pi-3-and-additional-network-dongle/438), it's not resin-wifi-connect specific, but maybe there are some useful pointers there.

Can you give some info about your specific use case?

**Comment by benoitguigal** [comment]
I have a project on Raspberry Pi 3 that requires WiFi connectivity and the type of connection workflow allowed by resin-wifi-connect. The device is located in a box made out of steel inside which the WiFi signal is weak. That's why I decided to connect a USB dongle with a Ralink chipset and an antenna that I can mount outside of the box. I want to be sure resin-wifi-connect uses the WiFi interface provided by the dongle and not the onboard WiFi interface.   

Running iwconfig, I can see that the onboard wifi is assigned wlan0 and the USB dongle is assigned wlan1. resin-wifi-connect picks up wlan1. This is the expected behavior but I do not know if it is deterministic or not ? Is there a way tune which interface is used ?

**Comment by alexandrosm** [comment]
Maybe we should make the wlan0 setting configurable?

**Comment by imrehg** [comment]
@alexandrosm looking at the code, it actually is already configurable, so that should solve half of @benoitguigal's problem: set a `PORTAL_INTERFACE` environment variable, and that will be picked up by `resin-wifi-connect` (by default `wlan0`).

Persistent names is an outstanding issue, that needs some more research ([another forum thread about that](https://forums.resin.io/t/persistent-interface-names/444/7)), my guess is that the onboard wifi adapter should come up usually earlier (but that's not good enough). Need to do more testing regarding this assumption!

**Comment by benoitguigal** [comment]
@alexandrosm @imrehg thank you for your answer. Indeed I will try to play around with the PORTAL_INTERFACE environment variable and read about persistent interface names. I will document my findings in the blog if it worth it :-)
